# file: .github/workflows/show-directory.yml
name: check-project
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  lint:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v4
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      #- run: make lint
      - run: make lint
  test:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v4
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      #- run: make lint
      - run: make test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@master
        with:
         node-version: 20
      - run: npm ci
      - uses: paambaati/codeclimate-action@v3.1.1
        env:
          CC_TEST_REPORTER_ID:  ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: make coverage

